[package]
name = "johnnydecimal"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
sanitise-file-name = "1.0.0"

[lints]
workspace = true
